#!/usr/bin/env bash

set -e
set -o verbose

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# BASH_IT
if [ ! -d ${HOME}/.bash_it ]; then
	git clone https://github.com/Bash-it/bash-it.git ${HOME}/.bash_it
fi

# NVM
if ! [ -x "$(command -v nvm)" ]; then
	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
	nvm install node
fi

# CEDICT
if [ ! -f ${HOME}/cedict_1_0_ts_utf-8_mdbg.txt ]; then
	wget https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz -O ${HOME}/cedict_1_0_ts_utf-8_mdbg.txt.gz
	gunzip ${HOME}/cedict_1_0_ts_utf-8_mdbg.txt.gz
fi

# APT
sudo apt install tmux docker docker-compose git golang ruby ruby-dev

# GO
go get github.com/spf13/hugo
go get github.com/hughgrigg/cedict-shuffler

